/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.mohammad.almahamid;

import java.io.IOException;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;

public class App {

    public static void main(String[] args) throws JsonParseException, JsonMappingException, IOException {
        if (args.length == 3) {
            // Path to the data file, e.g. data/data.xml
            final String DATA_FILE = args[0];
            // Path to the data file, e.g. operations/operations.xml
            final String OPERATIONS_FILE = args[1];
            // Path to the output file
            final String OUTPUT_FILE = args[2];
            JsonCalculator jsonCalculator = new JsonCalculator();
            jsonCalculator.Calculator(DATA_FILE, OPERATIONS_FILE, OUTPUT_FILE);

        } else {
            System.exit(1);
        }
    }
}
